[mgr]

prepend_keymap = [
	{ on = "<Esc>", run = [ "escape", "unyank" ] },
	{ on = "z", run = "plugin zz" },
]

append_keymap = [
	{ on = "<C-t>", run = "tab_create --current" },
	{ on = "<C-w>", run = "close" },
	{ on = "<A-Left>", run = "tab_switch -1 --relative" },
	{ on = "<A-Right>", run = "tab_switch +1 --relative" },
]
